"""Génération d'un PDF de rapport de match, à partir des données déjà calculées
(score, classement des joueurs) et du rapport rédigé par le LLM.

Pur Python (reportlab) : aucune dépendance système, testable hors ligne. Le PDF
ne fait que METTRE EN PAGE des données existantes — il n'en produit aucune.
"""
import os
from io import BytesIO
from xml.sax.saxutils import escape

import reportlab
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

# Helvetica (police PDF standard) ne couvre pas le latin étendu : un nom comme
# « Modrić » y devient un carré. On enregistre Vera (livrée avec reportlab, donc
# portable et sans ajout au dépôt), qui couvre ć/č/š/ž… ; repli sur Helvetica.
_FONT, _FONT_BOLD = "Helvetica", "Helvetica-Bold"
try:
    _fonts_dir = os.path.join(os.path.dirname(reportlab.__file__), "fonts")
    pdfmetrics.registerFont(TTFont("Vera", os.path.join(_fonts_dir, "Vera.ttf")))
    pdfmetrics.registerFont(TTFont("Vera-Bold", os.path.join(_fonts_dir, "VeraBd.ttf")))
    registerFontFamily("Vera", normal="Vera", bold="Vera-Bold")
    _FONT, _FONT_BOLD = "Vera", "Vera-Bold"
except Exception:  # pragma: no cover - repli si la police n'est pas disponible
    pass

_ACCENT = colors.HexColor("#4338ca")
_DIM = colors.HexColor("#566173")

_LABELS = {
    "fr": {
        "motm": "Homme du match",
        "ratings": "Notes des joueurs (score composite)",
        "tactics": "Suggestions tactiques",
        "player": "Joueur", "team": "Équipe", "pos": "Poste", "min": "Min", "rating": "Note",
        "by": "Généré par MatchIQ — le ML calcule les scores, le LLM les interprète.",
    },
    "en": {
        "motm": "Man of the match",
        "ratings": "Player ratings (composite score)",
        "tactics": "Tactical suggestions",
        "player": "Player", "team": "Team", "pos": "Position", "min": "Min", "rating": "Rating",
        "by": "Generated by MatchIQ — ML computes the scores, the LLM interprets them.",
    },
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("mq_title", parent=base["Title"], fontName=_FONT_BOLD, fontSize=20,
                                spaceAfter=2, textColor=colors.HexColor("#171a1f")),
        "sub": ParagraphStyle("mq_sub", parent=base["Normal"], fontName=_FONT, fontSize=9,
                              textColor=_DIM, spaceAfter=14),
        "h": ParagraphStyle("mq_h", parent=base["Heading2"], fontName=_FONT_BOLD, fontSize=11,
                             textColor=_ACCENT, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("mq_body", parent=base["Normal"], fontName=_FONT, fontSize=10, leading=15),
        "team": ParagraphStyle("mq_team", parent=base["Normal"], fontName=_FONT_BOLD, fontSize=10,
                               leading=15, spaceBefore=6, textColor=colors.HexColor("#171a1f")),
        "foot": ParagraphStyle("mq_foot", parent=base["Normal"], fontName=_FONT, fontSize=8,
                               textColor=_DIM, spaceBefore=18),
    }


def build_match_pdf(summary: dict, ranked: list[dict], report: dict, lang: str = "fr") -> bytes:
    """Compose le PDF et renvoie ses octets."""
    lang = lang if lang in _LABELS else "fr"
    lab = _LABELS[lang]
    st = _styles()

    teams = summary.get("teams") or {}
    home = (teams.get("home") or {}).get("name", "—")
    away = (teams.get("away") or {}).get("name", "—")
    goals = summary.get("goals") or {}
    score = f"{goals.get('home', '?')} - {goals.get('away', '?')}"
    league = (summary.get("league") or {}).get("name", "")
    date = (summary.get("date") or "")[:10]

    story = [
        Paragraph(f"{escape(home)} &nbsp;{score}&nbsp; {escape(away)}", st["title"]),
        Paragraph(escape(" · ".join(x for x in (league, date) if x)), st["sub"]),
    ]

    # Homme du match
    motm = ranked[0] if ranked else None
    if motm:
        story.append(Paragraph(lab["motm"], st["h"]))
        story.append(Paragraph(
            f"<b>{escape(motm['name'])}</b> — {escape(motm['position'])} · "
            f"{motm['composite_score']:.1f}/10", st["body"]))
        if report.get("motm_report"):
            story.append(Spacer(1, 4))
            story.append(Paragraph(escape(report["motm_report"]), st["body"]))

    # Tableau des notes
    story.append(Paragraph(lab["ratings"], st["h"]))
    head = ["#", lab["player"], lab["team"], lab["pos"], lab["min"], lab["rating"]]
    rows = [head] + [
        [str(i), p["name"], p["team_name"], p["position"], str(p.get("minutes", "")),
         f"{p['composite_score']:.1f}"]
        for i, p in enumerate(ranked, start=1)
    ]
    table = Table(rows, colWidths=[10 * mm, 55 * mm, 40 * mm, 28 * mm, 14 * mm, 16 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
        ("FONTNAME", (0, 1), (-1, -1), _FONT),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (4, 0), (5, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f7f9")]),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, _ACCENT),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)

    # Suggestions tactiques
    tactics = report.get("tactical_suggestions") or {}
    if tactics:
        story.append(Paragraph(lab["tactics"], st["h"]))
        for team_name, text in tactics.items():
            story.append(Paragraph(escape(team_name), st["team"]))
            story.append(Paragraph(escape(text), st["body"]))

    story.append(Paragraph(escape(lab["by"]), st["foot"]))

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=16 * mm,
        title=f"MatchIQ · {home} {score} {away}",
    )
    doc.build(story)
    return buf.getvalue()
