"""Génération d'un PDF de rapport de match, à partir des données déjà calculées
(score, classement des joueurs) et du rapport rédigé par le LLM.

Pur Python (reportlab) : aucune dépendance système, testable hors ligne. Le PDF
ne fait que METTRE EN PAGE des données existantes — il n'en produit aucune.
"""
import os
from io import BytesIO
from xml.sax.saxutils import escape

import reportlab
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

# Helvetica (police PDF standard) ne couvre pas le latin étendu : un nom comme
# « Modrić » y devient un carré. On enregistre Vera (livrée avec reportlab, donc
# portable et sans ajout au dépôt), qui couvre ć/č/š/ž… ; repli sur Helvetica.
_FONT, _FONT_BOLD = "Helvetica", "Helvetica-Bold"
try:
    _fonts_dir = os.path.join(os.path.dirname(reportlab.__file__), "fonts")
    pdfmetrics.registerFont(TTFont("Vera", os.path.join(_fonts_dir, "Vera.ttf")))
    pdfmetrics.registerFont(TTFont("Vera-Bold", os.path.join(_fonts_dir, "VeraBd.ttf")))
    registerFontFamily("Vera", normal="Vera", bold="Vera-Bold")
    _FONT, _FONT_BOLD = "Vera", "Vera-Bold"
except Exception:  # pragma: no cover - repli si la police n'est pas disponible
    pass

_ACCENT = colors.HexColor("#4338ca")
_DIM = colors.HexColor("#566173")

_LABELS = {
    "fr": {
        "motm": "Homme du match",
        "insights": "Faits marquants",
        "ratings": "Notes des joueurs (score composite)",
        "tactics": "Suggestions tactiques",
        "player": "Joueur", "team": "Équipe", "pos": "Poste", "min": "Min", "rating": "Note",
        "by": "Généré par MatchIQ — le ML calcule les scores, le LLM les interprète.",
    },
    "en": {
        "motm": "Man of the match",
        "insights": "Key facts",
        "ratings": "Player ratings (composite score)",
        "tactics": "Tactical suggestions",
        "player": "Player", "team": "Team", "pos": "Position", "min": "Min", "rating": "Rating",
        "by": "Generated by MatchIQ — ML computes the scores, the LLM interprets them.",
    },
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("mq_title", parent=base["Title"], fontName=_FONT_BOLD, fontSize=20,
                                spaceAfter=2, textColor=colors.HexColor("#171a1f")),
        "sub": ParagraphStyle("mq_sub", parent=base["Normal"], fontName=_FONT, fontSize=9,
                              textColor=_DIM, spaceAfter=14),
        "h": ParagraphStyle("mq_h", parent=base["Heading2"], fontName=_FONT_BOLD, fontSize=11,
                             textColor=_ACCENT, spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("mq_body", parent=base["Normal"], fontName=_FONT, fontSize=10, leading=15),
        "team": ParagraphStyle("mq_team", parent=base["Normal"], fontName=_FONT_BOLD, fontSize=10,
                               leading=15, spaceBefore=6, textColor=colors.HexColor("#171a1f")),
        "foot": ParagraphStyle("mq_foot", parent=base["Normal"], fontName=_FONT, fontSize=8,
                               textColor=_DIM, spaceBefore=18),
    }


def build_match_pdf(summary: dict, ranked: list[dict], report: dict, lang: str = "fr") -> bytes:
    """Compose le PDF et renvoie ses octets."""
    lang = lang if lang in _LABELS else "fr"
    lab = _LABELS[lang]
    st = _styles()

    teams = summary.get("teams") or {}
    home = (teams.get("home") or {}).get("name", "—")
    away = (teams.get("away") or {}).get("name", "—")
    goals = summary.get("goals") or {}
    score = f"{goals.get('home', '?')} - {goals.get('away', '?')}"
    league = (summary.get("league") or {}).get("name", "")
    date = (summary.get("date") or "")[:10]

    story = [
        Paragraph(f"{escape(home)} &nbsp;{score}&nbsp; {escape(away)}", st["title"]),
        Paragraph(escape(" · ".join(x for x in (league, date) if x)), st["sub"]),
    ]

    # Homme du match
    motm = ranked[0] if ranked else None
    if motm:
        story.append(Paragraph(lab["motm"], st["h"]))
        story.append(Paragraph(
            f"<b>{escape(motm['name'])}</b> — {escape(motm['position'])} · "
            f"{motm['composite_score']:.1f}/10", st["body"]))
        if report.get("motm_report"):
            story.append(Spacer(1, 4))
            story.append(Paragraph(escape(report["motm_report"]), st["body"]))

    # Faits marquants (déterministes)
    insights = report.get("insights") or []
    if insights:
        story.append(Paragraph(lab["insights"], st["h"]))
        for item in insights:
            story.append(Paragraph(f"• {escape(item)}", st["body"]))

    # Tableau des notes
    story.append(Paragraph(lab["ratings"], st["h"]))
    head = ["#", lab["player"], lab["team"], lab["pos"], lab["min"], lab["rating"]]
    rows = [head] + [
        [str(i), p["name"], p["team_name"], p["position"], str(p.get("minutes", "")),
         f"{p['composite_score']:.1f}"]
        for i, p in enumerate(ranked, start=1)
    ]
    table = Table(rows, colWidths=[10 * mm, 55 * mm, 40 * mm, 28 * mm, 14 * mm, 16 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD),
        ("FONTNAME", (0, 1), (-1, -1), _FONT),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (4, 0), (5, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f7f9")]),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, _ACCENT),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)

    # Suggestions tactiques
    tactics = report.get("tactical_suggestions") or {}
    if tactics:
        story.append(Paragraph(lab["tactics"], st["h"]))
        for team_name, text in tactics.items():
            story.append(Paragraph(escape(team_name), st["team"]))
            story.append(Paragraph(escape(text), st["body"]))

    story.append(Paragraph(escape(lab["by"]), st["foot"]))

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=16 * mm,
        title=f"MatchIQ · {home} {score} {away}",
    )
    doc.build(story)
    return buf.getvalue()


_SCOUT_LABELS = {
    "fr": {"title": "Fiche de scouting", "summary": "Résumé exécutif",
           "vs_pos": "Profil vs moyenne du poste", "cat": "Catégorie", "player": "Joueur",
           "avg": "Moyenne poste", "delta": "Écart", "similar": "Profils proches",
           "alerts": "Écarts de performance", "sim": "Similarité",
           "by": "Fiche générée par MatchIQ — données calculées, jamais inventées."},
    "en": {"title": "Scouting report", "summary": "Executive summary",
           "vs_pos": "Profile vs position average", "cat": "Category", "player": "Player",
           "avg": "Position avg", "delta": "Delta", "similar": "Similar profiles",
           "alerts": "Performance outliers", "sim": "Similarity",
           "by": "Report generated by MatchIQ — computed data, never invented."},
}


def build_scouting_pdf(data: dict, lang: str = "fr") -> bytes:
    """Fiche de scouting joueur (une page) : résumé exécutif, comparaison à la
    moyenne du poste, profils proches et écarts de performance. Ne met en page
    que des données déjà calculées (reporting/scouting.py)."""
    lang = lang if lang in _SCOUT_LABELS else "fr"
    lab = _SCOUT_LABELS[lang]
    st = _styles()
    p = data["player"]

    story = [
        Paragraph(escape(p["name"]), st["title"]),
        Paragraph(escape(f"{lab['title']} · {p['team_name']} · {p['position']}"), st["sub"]),
    ]

    # Bandeau chiffres clés
    kpi = [[
        f"{p['average_score']:.1f}/10", f"{p['matches_played']}", f"{p['pool_average']:.1f}",
    ]]
    kpi_head = [["Note moyenne" if lang == "fr" else "Avg rating",
                 "Matchs" if lang == "fr" else "Matches",
                 "Moyenne poste" if lang == "fr" else "Position avg"]]
    ktable = Table(kpi_head + kpi, colWidths=[45 * mm, 45 * mm, 45 * mm])
    ktable.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), _FONT), ("FONTNAME", (0, 1), (-1, 1), _FONT_BOLD),
        ("FONTSIZE", (0, 0), (-1, 0), 8), ("FONTSIZE", (0, 1), (-1, 1), 16),
        ("TEXTCOLOR", (0, 0), (-1, 0), _DIM), ("TEXTCOLOR", (0, 1), (-1, 1), _ACCENT),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"), ("TOPPADDING", (0, 1), (-1, 1), 2),
    ]))
    story.append(ktable)

    # Résumé exécutif
    story.append(Paragraph(lab["summary"], st["h"]))
    story.append(Paragraph(escape(data["exec_summary"]), st["body"]))

    # Comparaison à la moyenne du poste
    features = data.get("features") or {}
    if features:
        story.append(Paragraph(f"{lab['vs_pos']} ({data['baseline_n']})", st["h"]))
        rows = [[lab["cat"], lab["player"], lab["avg"], lab["delta"]]]
        for k in sorted(features, key=lambda k: -(features[k] - data["baseline"].get(k, 0.0))):
            base = data["baseline"].get(k, 0.0)
            delta = features[k] - base
            rows.append([k, f"{features[k]:.2f}", f"{base:.2f}",
                         f"{'+' if delta >= 0 else ''}{delta:.2f}"])
        table = Table(rows, colWidths=[60 * mm, 30 * mm, 30 * mm, 25 * mm], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), _ACCENT), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), _FONT_BOLD), ("FONTNAME", (0, 1), (-1, -1), _FONT),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5), ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f7f9")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)

    # Profils proches
    similar = data.get("similar") or []
    if similar:
        story.append(Paragraph(lab["similar"], st["h"]))
        for s in similar:
            story.append(Paragraph(
                f"• {escape(s['name'])} ({escape(s.get('team_name') or '')}) — "
                f"{lab['sim']} {round(s['similarity'] * 100)}%", st["body"]))

    # Écarts de performance
    anomalies = (data.get("anomalies") or {}).get("anomalies") or []
    if anomalies:
        story.append(Paragraph(lab["alerts"], st["h"]))
        for a in anomalies:
            kind = ("Record" if a["type"] == "record" else "Contre-performance") if lang == "fr" \
                else ("Career-high" if a["type"] == "record" else "Below standard")
            story.append(Paragraph(
                f"• {kind} vs {escape(a.get('opponent_name') or '?')} — "
                f"{a['composite_score']:.1f} (z {a['z']:+.1f})", st["body"]))

    story.append(Paragraph(escape(lab["by"]), st["foot"]))

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=16 * mm,
        title=f"MatchIQ · {lab['title']} · {p['name']}",
    )
    doc.build(story)
    return buf.getvalue()
